version: '2'
services:
  rabbitmq:
    image: rabbitmq:3
    environment:
      - RABBITMQ_DEFAULT_VHOST=openquake 
      - RABBITMQ_DEFAULT_USER=openquake
      - RABBITMQ_DEFAULT_PASS=openquake
    networks:
      - oq-cluster-net
  # Engine is not actually executed and is
  # exposed only to make sure it is built via
  # docker-compose build
  engine:
    build:
      context: .
      dockerfile: Dockerfile.engine
    image: openquake/engine
    command: '-c true'
  master:
    build:
      context: .
      dockerfile: Dockerfile.master
    image: openquake/engine-master
    # Uncomment to enable auth in WebUI/API
    # environment:
    #   - LOCKDOWN=true
    # volumes:
    # Uncomment to use a local copy of the oq-engine
    #   - ./path/to/oq-engine/openquake:/opt/openquake/lib/python3.6/site-packages/openquake
    # Uncomment to use a custom openquake.cfg
    #   - ./path/to/openquake.cfg:/etc/openquake/openquake.cfg
    networks:
      - oq-cluster-net
    ports:
      - 8800:8800
    depends_on:
      - rabbitmq
  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    image: openquake/engine-worker
    # volumes:
    # Uncomment to use a local copy of the oq-engine
    #   - ./path/to/oq-engine/openquake:/opt/openquake/lib/python3.6/site-packages/openquake
    # Uncomment to use a custom openquake.cfg
    #   - ./path/to/openquake.cfg:/etc/openquake/openquake.cfg
    environment:
      - OQ_RABBITMQ_HOST=rabbitmq
    entrypoint: ["./celery-wait.sh"]
    networks:
      - oq-cluster-net
    depends_on:
      - rabbitmq
      - master

networks:
  oq-cluster-net:
