language: python
python:
    - 2.7

services:
    - docker

script:
    - cd ./windows/nsis-installer && mkdir -p src/py src/py27
    - docker build --rm=true -t oq-nsis -f docker/Dockerfile .
    - docker run -v $(pwd):/io -t --rm oq-nsis

