
language: python
python:
    - 2.7

services:
    - docker

script:
    - cd $TRAVIS_BUILD_DIR/oq-docker
    - docker build --rm=true -t openquake-centos7 -f Dockerfile.centos .
    - docker run --rm -i -t openquake-centos7 /opt/openquake/bin/oq --version
    - docker rmi openquake-centos7
    # NSIS installer
    - cd $TRAVIS_BUILD_DIR/installers/windows/nsis
    - docker build --rm=true -t oq-nsis -f docker/Dockerfile .
    - docker run --rm -t -i oq-nsis /usr/bin/wine python -c 'import pip; print(pip.__version__)'
    - docker rmi oq-nsis
