name: Linux build setproctitle
on:
  push:
jobs:
  build_GDAL: 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [36, 37, 38]
    container: 
      image: quay.io/pypa/manylinux1_x86_64
      env: 
        GEM_SET_PY: ${{ matrix.python-version }}
      volumes:
        - /home/runner/output:/io
    steps:
      - uses: actions/checkout@v1
      - name: build gdal wheel
        run: |
          bash -x wheels/builders/setproctitle.sh
      - name: Upload wheel
        uses: actions/upload-artifact@v1
        with:
          name: gdal wheel linux
          path: /home/runner/output
