name: build gdal whl
on:
  push:
jobs:
  Matrix-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #os: [macos-latest, windows-latest, ubuntu-latest]
        os: [macos-latest]
        #python-version: [3.6, 3.7, 3.8]
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup pip and wheel environments
        run: |
          pip install -U pip wheel setuptools auditwheel
          #
          mkdir src
          cd src
          cp ../wheels/builders/gdal/setup.py gdal-3.1.2/swig/python/setup.py
          cp ../wheels/builders/gdal/gdalinit.py gdal-3.1.2/swig/python/osgeo/__init__.py
          cd gdal-3.1.2/swig/python
          pip install -U numpy==1.18.2
      - name: build expat geos and proj
        run: |
          mkdir src
          cd src
          curl -f -L -O https://github.com/libexpat/libexpat/releases/download/R_2_2_9/expat-2.2.9.tar.bz2
          tar xjf expat-2.2.9.tar.bz2
          cd expat-2.2.9
          ./configure --prefix=/usr/local
          make -j 2
          sudo make install
          curl -f -L -O https://download.osgeo.org/geos/geos-3.8.1.tar.bz2 
          tar jxf geos-3.8.1.tar.bz2
          cd geos-3.8.1
          ./configure --prefix=/usr/local
          make -j $NPROC
          sudo make install
          curl -f -L -O https://download.osgeo.org/proj/proj-6.3.2.tar.gz
          tar xzf proj-6.3.2.tar.gz
          cd proj-6.3.2
          ./configure  --prefix=/usr/local
          make -j $NPROC
          sudo make install
      - name: compile GDAL 3.1.2 from source pip environments
        run: |
          cd src
          curl -f -L -O  https://download.osgeo.org/gdal/3.1.2/gdal-3.1.2.tar.gz
          tar xzf gdal-3.1.2.tar.gz
          cd gdal-3.1.2
          ./configure \
           --with-threads \
           --disable-debug \
           --disable-static \
           --with-libtiff \
           --with-libtool \
           --with-opencl \
           --with-jpeg \
           --with-gif \
           --with-png \
           --with-geotiff=internal \
           --with-sqlite3 \
           --with-pcraster=internal \
           --with-pcidsk=internal \
           --with-pam \
           --with-geos=/usr/local/bin/geos-config \
           --with-proj=/usr/local \
           --with-expat=/usr/local \
           --with-libjson-c \
           --with-libiconv-prefix=/usr \
           --with-libz=/usr \
           --with-curl=curl-config \
           --without-grass \
           --without-libgrass \
           --without-jpeg12 \
           --without-jasper \
           --with-armadillo=no \
           --with-qhull=no \
           --without-mysql \
           --without-perl \
           --without-python
          make -j 2
          sudo make install
          #test gdal installation
          gdalinfo --formats
          gdal-config --version
