name: Package Windows for oq-engine
on:
  workflow_dispatch:
jobs:
  Build_Installer:
    runs-on: windows-latest
    env:
      GIT_BRANCH: ${{ github.ref }}
      GIT_COMMIT_SHA: ${{ github.sha }}
    steps:
      - name: Output Variables
        run: |
          echo "${Env:GIT_BRANCH}"
      - name: Set up Python using embedded distribution and create Installer
        env:
          GIT_BRANCH: ${{ github.ref }}
          GIT_COMMIT_SHA: ${{ github.sha }}
        run: |
          Write-Host "Working Path: ${Env:GITHUB_WORKSPACE}"
          $branchName = $Env:GITHUB_REF -replace 'refs/heads/', ''
          Write-Host "Branch: ${branchName}"
          Write-Host "CURRENT_BRANCH=${branchName}" >> $Env:GITHUB_ENV
          Write-Host "Branch: ${branchName}"
          cd C:\Users\runneradmin
          curl  https://www.python.org/ftp/python/3.8.10/python-3.8.10-embed-amd64.zip --output python.zip
          where.exe unzip.exe
          unzip.exe python.zip -d python
          echo "install pip and wheel and markdown"
          cd python
          curl https://bootstrap.pypa.io/get-pip.py --output get-pip.py
          .\python.exe .\get-pip.py
          mv .\python38._pth .\python._pth.old
          $Env:PY_PIP = "C:\Users\runneradmin\python\Scripts"
          $Env:PY_LIBS = "C:\Users\runneradmin\python\Lib;C:\Users\runneradmin\python\Lib\site-package"
          $Env:PY_HOME = "C:\Users\runneradmin\python"
          $ENV:PATH="C:\Users\runneradmin\python\Scripts;$ENV:PATH"
          .\python.exe -m pip install pip wheel --upgrade
          .\python.exe -m pip install markdown==3.2.2
          Set-Alias -Name python -Value C:\Users\runneradmin\python\python.exe
          Set-Alias -Name pip -Value C:\Users\runneradmin\python\Scripts\pip.exe
          cd ~
          git clone --depth=1 -b ${branchName} https://github.com/gem/oq-builders
          cd .\oq-builders\installers\windows\nsis\
          mkdir .\oq-dist\engine
          git clone --depth=1 https://github.com/gem/oq-engine.git
          cd oq-engine
          Copy-Item -Path ".\install.py" -Destination "C:\Users\runneradmin\oq-builders\installers\windows\nsis\oq-dist\engine" -Recurse
          python -c "import sys; print(sys.version)"
          python -m pip install install -r requirements-py38-win64.txt
          cd ..
          echo "Downloading standalone apps"
          $app = ("oq-platform-standalone", "oq-platform-ipt", "oq-platform-taxonomy", "oq-platform-taxtweb")
          foreach ($element in $app) {
          git clone --depth=1 https://github.com/gem/$element.git
              python -m pip wheel --disable-pip-version-check --no-deps -w oq-dist/tools ./$element
              if ( $element -eq "oq-platform-taxtweb" )
              {
                $env:PYBUILD_NAME = "oq-taxonomy"
                echo ${env:PYBUILD_NAME}
                python -m pip -q wheel --disable-pip-version-check --no-deps -w oq-dist/tools ./$element
              }
          }
          cd ~
          cd .\oq-builders\installers\windows\nsis
          echo "Generating NSIS installer with oq version and time of git"
          $version = Select-String -Path .\oq-engine\openquake\baselib\__init__.py -Pattern '__version__ ='
          $pattern = "(?<=\').+?(?=\')"
          $inst_version = [regex]::Matches($version, $pattern).Value
          $time_of_git = git -C .\oq-engine log -n1 --pretty='format:%cd' --date=format:'%y%m%d%H%M'
          Write-Host "version: ${inst_version} and time: ${time_of_git}"
          (Get-Content -Path .\installer.nsi.ist -Raw) -replace 'CHANGETIME', $time_of_git -replace 'CHANGEHERERELEASE', $inst_version | Set-Content -Path .\installer.nsi
          Write-Host "Create portable environment for engine"
          cd ~
          mkdir package
          cd package
          curl  https://www.python.org/ftp/python/3.8.10/python-3.8.10-embed-amd64.zip --output python.zip
          unzip.exe python.zip -d python
          echo "install pip and wheel"
          cd python
          curl https://bootstrap.pypa.io/get-pip.py --output get-pip.py
          .\python.exe .\get-pip.py
          Write-Host "mv .\python38._pth C:\Users\runneradmin\package\python._pth.old"
          mv .\python38._pth .\python._pth.old
          $env:PY_PIP = "C:\Users\runneradmin\package\python\Scripts"
          $env:PY_LIBS = "C:\Users\runneradmin\package\python\Lib;C:\Users\runneradmin\python\Lib\site-package"
          $env:PY_HOME = "C:\Users\runneradmin\package\python"
          $env:PATH="C:\Users\runneradmin\package\python\Scripts;$ENV:PATH"
          echo ${env:PY_HOME}
          echo ${env:PATH}
          .\python.exe -m pip install wheel --upgrade
          .\python.exe -m pip install markdown==3.2.2
          Set-Alias -Name python -Value C:\Users\runneradmin\python\python.exe
          Set-Alias -Name pip -Value C:\Users\runneradmin\python\Scripts\pip.exe
          cd ..
          python -m markdown "C:\Users\runneradmin\oq-builders\installers\windows\nsis\oq-engine\README.md" > .\README.html
          Write-Host "Copy the wheel created for the standalone"
          Copy-Item -Path "C:\Users\runneradmin\oq-builders\installers\windows\nsis\oq-dist" -Destination ".\" -Recurse
          cd oq-dist
          cd ..
          $files = @(Get-ChildItem .\oq-dist\engine\*.whl)
          $files.Name > .\oq-dist\engine\index.txt
          $files = @(Get-ChildItem .\oq-dist\tools\*.whl)
          $files.Name > .\oq-dist\tools\index.txt
          curl.exe "https://docs.openquake.org/manuals/OpenQuake%20Manual%20(master).pdf" --output "Openquake manual.pdf"
          Copy-Item -Path "C:\Users\runneradmin\oq-builders\installers\windows\nsis\installer.nsi" -Destination ".\"
          Copy-Item -Path "C:\Users\runneradmin\oq-builders\installers\windows\nsis\openquake*.*" -Destination ".\"
          Copy-Item -Path "C:\Users\runneradmin\oq-builders\installers\windows\nsis\oq-*.*" -Destination ".\"
          Copy-Item -Path "C:\Users\runneradmin\oq-builders\installers\windows\nsis\LICENSE.txt" -Destination ".\"
          makensis /V4 installer.nsi
          mkdir out
          $Install = Get-ChildItem -Filter *.exe
          Get-FileHash $Install | Select-Object Hash
          $hash = Get-FileHash $Install -Algorithm SHA256
          $sha256 = $hash.Hash
          $Name = $Install.Name
          $Outfile = $Install.Name + ".sha256"
          Write-Output $hash.Hash  $Install.Name > $Outfile
          Copy-Item *.exe .\out
          Copy-Item $Outfile .\out
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Installer
          path: C:\Users\runneradmin\package\out

  Test_Installer:
    needs: Build_Installer
    runs-on: windows-latest
    steps:
      - name: Download Windows Installer from build job
        uses: actions/download-artifact@v2
        with:
          name: Installer
      - name: Execute the Installer
        run: |
          $Install = Get-ChildItem -Filter *.exe
          Start-Process -FilePath $Install.Fullname -ArgumentList "/S" -Wait
          cd "C:\Program Files\OpenQuake\"
          $env:PATH="C:\Program Files\OpenQuake\python\Scripts"
          echo ${env:PATH}
          pwd
      - name: Run oq
        run: |
          set mypath=C:\Program Files\OpenQuake
          set PATH=%mypath%\python;%mypath%\python\Scripts;%PATH%
          echo %PATH%
          oq --version
          oq.exe engine --run "https://downloads.openquake.org/pkgs/test_event_based_risk_inputs_bc.zip"
        shell: cmd

  Upload_Installer:
    needs: Build_Installer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download Windows Installer from build job
        uses: actions/download-artifact@v2
        with:
          name: Installer
      - name: rsync to downloads.openquake.org
        shell: bash
        env:
          DOWNLOAD_SSH: ${{ secrets.DOWNLOAD_ARTIFACTS }}
        run: |
          gpg --quiet --batch --yes --decrypt --passphrase="$DOWNLOAD_SSH" --output ./.deploy_rsa ./.oq_builders.enc
          chmod 600 ./.deploy_rsa
          eval $(ssh-agent -s) && ssh-add ./.deploy_rsa
          rsync -e 'ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p 332' -ax OpenQuake_Engine* ftp@downloads.openquake.org:/mnt/box/openquake/downloads/pkgs/windows/oq-engine/
