name: Linux build GDAL 
on:
  push:
    branches: [ gdal ]
jobs:
  build_whl: 
    runs-on: ubuntu-latest
    container: 
      image: quay.io/pypa/manylinux2010_x86_64
      volumes:
        - $(pwd):/io
    steps:
      - uses: actions/checkout@v1
      - name: 
        run: |
          uname -a
          pwd
          ls -lrt
          bash -x wheels/builders/gdal.sh
