name: Linux build GDAL 
on:
  push:
    branches: [ gdal ]
jobs:
  build_GDAL: 
    runs-on: ubuntu-latest
    container: 
      image: quay.io/pypa/manylinux1_x86_64
      #volumes:
      #  - /home/runner/work/output:/io
    steps:
      - uses: actions/checkout@v1
      - name: 
        run: |
          bash -x wheels/builders/gdal.sh
          cd wheels/wheelhouse
          ls -lrt
          pwd
