name: brew method for macOS GDAL whl 
on:
  workflow_dispatch:
#    inputs:
#      gdal-ref:
#        description: GDAL Version
#        default: 3.3.3
#        required: true
# pull_request:
#    branches:
#      - master
# push:
#    branches:
#     - python3.9
jobs:
  wheel_of_GDAL:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-11]
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install gdal using brew and build wheel
        #env:
          #GDAL_REF: ${{ github.event.inputs.gdal-ref }}
        run: |
          #$gdalref = ${{ github.event.inputs.gdal-ref }}
          echo "Input GDAL version: $gdalref"
          echo "brew install gdal"
          brew install gdal
          #
          #test gdal installation
          echo " gdalinfo --version"
          gdalinfo --version
          pip3 install -U pip wheel setuptools delocate
          pip3 install numpy
          pip3 download GDAL==3.3.3
          tar -xvzf GDAL-3.3.3.tar.gz
          cd GDAL-3.3.3
          pwd
          python setup.py build
          python setup.py install
          pip wheel --no-deps --no-binary :all: -w output .
          cd output
          delocate-wheel -w ~/src/whl GDAL*.whl
      - name: Test Gdal with python
        run: python3 -c "import osgeo.gdal; print(osgeo.gdal.VersionInfo())"
      - name: Upload artifacts of wheel
        uses: actions/upload-artifact@v2
        with:
          name: gdal wheel macos
          path: ~/src/whl/
