name: compile macOS build GDAL whl
on:
  workflow_dispatch:
 #schedule:
   #- cron: "0 5 * * 1"
jobs:
  GDAL-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #os: [macos-latest, windows-latest, ubuntu-latest]
        os: [macos-10.15]
        python-version: [3.6, 3.7, 3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: build expat geos and proj
        run: |
          mkdir src
          cd src
          curl -f -L -O https://github.com/libexpat/libexpat/releases/download/R_2_2_9/expat-2.2.9.tar.bz2
          tar xjf expat-2.2.9.tar.bz2
          cd expat-2.2.9
          ./configure 
          make -j 4
          sudo make install
          curl -f -L -O https://download.osgeo.org/geos/geos-3.8.1.tar.bz2 
          tar jxf geos-3.8.1.tar.bz2
          cd geos-3.8.1
          ./configure --enable-python
          make -j 4
          sudo make install
          which geos-config
          curl -f -L -O https://download.osgeo.org/proj/proj-6.3.2.tar.gz
          tar xzf proj-6.3.2.tar.gz
          cd proj-6.3.2
          ./configure 
          make -j 4
          sudo make install
      - name: compile GDAL 3.2.2 from source pip environments
        run: |
          cd src
          curl -f -L -O  https://download.osgeo.org/gdal/3.2.2/gdal-3.2.2.tar.gz
          tar xzf gdal-3.2.2.tar.gz
          cd gdal-3.2.2
          ./configure \
           --with-threads \
           --disable-debug \
           --disable-static \
           --with-libtiff \
           --with-libtool \
           --with-opencl \
           --with-jpeg \
           --with-gif \
           --with-png \
           --with-geotiff \
           --with-sqlite3 \
           --with-pcraster=internal \
           --with-pcidsk=internal \
           --with-pam \
           --with-geos=/usr/local/bin/geos-config \
           --with-proj=/usr/local \
           --with-expat=/usr/local \
           --with-freexl \
           --with-libjson-c \
           --with-libiconv-prefix \
           --with-libz \
           --with-curl=/usr/bin/curl-config \
           --without-grass \
           --without-libgrass \
           --without-jpeg12 \
           --without-jasper \
           --with-armadillo=no \
           --with-qhull=no \
           --with-pg=yes \
           --without-mysql \
           --without-perl \
           --with-macosx-framework
          make -j 4
          sudo make install
          echo 'export PATH=/Library/Frameworks/GDAL.framework/Versions/3.2/Programs:$PATH' >> ~/.z_profile
          source ~/.z_profile
          #test gdal installation
          ls -lrt  /Library/Frameworks/GDAL.framework/Versions/3.2/*
          ls -lrt /Library/Frameworks/GDAL.framework/Versions/3.2/Headers 
          ls -lrt /Library/Frameworks/GDAL.framework/Versions/3.2/unix/lib 
          ls -lrt /Library/Frameworks/GDAL.framework/Versions/3.2/unix/bin/gdal-config  
          echo " gdalinfo --version"
          gdalinfo --version
          pip3 install -U pip wheel setuptools delocate
          pip3 install numpy==1.18.2
          pip3 download GDAL==3.2.2
          tar -xvzf GDAL-3.2.2.tar.gz
          cd GDAL-3.2.2
          pwd
          cp /Users/runner/work/oq-builders/oq-builders/wheels/builders/gdal/setup_mac.py ./setup.py
          export GDAL_DATA=/Library/Frameworks/GDAL.framework/Versions/3.2/Resources/gdal/gdal
          python setup.py build_ext -I/Library/Frameworks/GDAL.framework/Versions/3.2/Headers -L/Library/Frameworks/GDAL.framework/Versions/3.2/unix/lib --gdal-config /Library/Frameworks/GDAL.framework/Versions/3.2/unix/bin/gdal-config
          python setup.py build
          python setup.py install
          pip wheel --no-deps --no-binary :all: -w output .
          cd output
          delocate-wheel -w ~/src/whl GDAL*.whl
      - name: Upload wheel
        uses: actions/upload-artifact@v2
        with:
          name: gdal wheel macos
          path: ~/src/whl/
