name: Wheels for engine
on:
  push:
  workflow_dispatch:
    inputs:
      git-ref:
        description: Git Ref
        default: master
        required: true

env:
  PROJ_VERSION: "9.0.1"

jobs:
  build_wheels:
    name: M1 pyproj wheel
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
         include:
          #- os: macos-10.15
          # arch: universal2
          # cmake_osx_architectures: x86_64
          # cibuild_architectures: universal2
          - os: m1Gem
            arch: arm64
            cmake_osx_architectures: arm64
            cibuild_architectures: arm64
        # - os: macos-10.15
        #   arch: universal2
        #   cmake_osx_architectures: "x86_64;arm64"

    steps:
      - uses: actions/checkout@v3
      - name: Download pyproj sources
        run: |
           export PIP_DEFAULT_TIMEOUT=100
           pip3 download --no-deps --no-binary :all: pyproj==3.3.1
           tar -zxvf pyproj-3.3.1.tar.gz

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.8.0
        with:
          package-dir: ./pyproj-3.3.1
          output-dir: wheelhouse
        env:
          CIBW_SKIP: "*musllinux* pp*-win*"
          CIBW_ARCHS: ${{ matrix.arch }}
          CIBW_BUILD: cp39-*
          CIBW_BUILD_VERBOSITY: 2
          #CIBW_ARCHS_MACOS: universal2
          CIBW_ENVIRONMENT_MACOS:
            PROJ_WHEEL=true
            PROJ_NETWORK=ON
            PROJ_VERSION=${{ env.PROJ_VERSION }}
            PROJ_DIR=${GITHUB_WORKSPACE}/pyproj/proj_dir
            MACOSX_DEPLOYMENT_TARGET=10.9
            CMAKE_OSX_ARCHITECTURES='${{ matrix.cmake_osx_architectures }}'
            LDFLAGS="${LDFLAGS} -Wl,-rpath,${GITHUB_WORKSPACE}/pyproj/proj_dir/lib"
          CIBW_BEFORE_ALL_MACOS: bash ./wheels/builders/proj-compile-wheels.sh
          CIBW_TEST_REQUIRES: cython pytest oldest-supported-numpy pandas xarray
          CIBW_BEFORE_TEST: python3.9 -m pip install shapely~=1.7.1 || echo "Shapely install failed"
          CIBW_TEST_COMMAND: >
            pyproj -v &&
            python -c "import pyproj; pyproj.Proj(init='epsg:4269')"  &&
            cp -r {package}/test . &&
            python3.9 -m pytest test -v -s

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
          retention-days: 1
