name: M1 pyproj wheel
on:
  push:
  workflow_dispatch:
    inputs:
      git-ref:
        description: Git Ref
        default: master
        required: true

env:
  PROJ_VERSION: "8.2.1"
  PROJ_DIR: ${GITHUB_WORKSPACE}/pyproj/pyproj/proj_dir

jobs:
  build_wheels:
    name: M1 pyproj wheel
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
         include:
          #- os: macos-10.15
          # arch: universal2
          # cmake_osx_architectures: x86_64
          # cibuild_architectures: universal2
          - os: ARM64
            arch: arm64
            cmake_osx_architectures: arm64
            cibuild_architectures: arm64
        # - os: macos-10.15
        #   arch: universal2
        #   cmake_osx_architectures: "x86_64;arm64"

    steps:
      - uses: actions/checkout@v3
      - name: Download pyproj sources
        env:
          PROJ_VERSION: "8.2.1"
          PROJ_DIR: ${GITHUB_WORKSPACE}/pyproj/pyproj/proj_dir
        run: |
           export PIP_DEFAULT_TIMEOUT=100
           export PROJ_WHEEL=true
           export PROJ_NETWORK=ON
           export PROJ_VERSION=${{ env.PROJ_VERSION }}
           export PROJ_DIR=${{ env.PROJ_DIR }}
           export MACOSX_DEPLOYMENT_TARGET=10.9
           export CMAKE_OSX_ARCHITECTURES='arm64'
           export LDFLAGS="${LDFLAGS} -Wl,-rpath,${GITHUB_WORKSPACE}/pyproj/pyproj/proj_dir/lib"
           #
           echo "env of variable"
           env
           #
           echo "PROJ_DIR: " ${PROJ_DIR}
           echo "PROJ_DIR: " ${{ env.PROJ_DIR }}
           curl -L -v -o pyproj-3.3.1.tar.gz https://github.com/pyproj4/pyproj/archive/refs/tags/3.3.1.tar.gz
           tar -zxvf pyproj-3.3.1.tar.gz
           cp ./wheels/builders/proj-compile-wheels.sh pyproj-3.3.1/ci
           mv pyproj-3.3.1 pyproj
           cd pyproj
           echo "main folder `pwd`"
           pwd
           echo "======="
           #
           # compile proj
           #
           bash ./ci/proj-compile-wheels.sh
           #
           echo "list content of ${PROJ_DIR}  `ls ${PROJ_DIR}`"
           #
           python3.9 -m venv venv
           source venv/bin/activate
           pip install -U pip wheel setuptools delocate cython pytest 
           pip install -U oldest-supported-numpy pandas xarray
           #
           # make wheel
           #
           echo "check INTERNAL_PROJ_DIR"
           grep INTERNAL_PROJ_DIR setup.py
           #
           python -m pip wheel . --wheel-dir=./output --no-deps -vv
           echo "list of output folder `ls ./output`"
           delocate-listdeps ./output/*.whl 
           delocate-wheel --require-archs arm64 ./output/*.whl -w ~/repaired_wheel
           #
           echo "list of repaired_wheel folder `ls ~/repaired_wheel`"
           # test wheel
           which python3
           pip freeze
           pyproj -v 
           python3 -c "import pyproj; pyproj.Proj(init='epsg:4269')" 
           pytest test -v -s
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: pyproj_whl
          path: ~/repaired_wheel/*.whl
          retention-days: 3
