name: M1 pyproj wheel
on:
  push:
  workflow_dispatch:
    inputs:
      git-ref:
        description: Git Ref
        default: master
        required: true

env:
  PROJ_VERSION: "8.2.1"
  PROJ_DIR: ${GITHUB_WORKSPACE}/pyproj/pyproj/proj_dir

jobs:
  build_wheels:
    name: M1 pyproj wheel
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ARM64]
        python-version: [3.9]
          #runs-on: ${{ matrix.os }}
          #strategy:
          #  fail-fast: false
          #  matrix:
          #     include:
          #      #- os: macos-10.15
          # arch: universal2
          # cmake_osx_architectures: x86_64
          # cibuild_architectures: universal2
          #      - os: ARM64

    steps:
      - uses: actions/checkout@v3
      - name: Download pyproj sources and install it
        env:
          PROJ_VERSION: "8.2.1"
          PROJ_DIR: ${GITHUB_WORKSPACE}/pyproj/pyproj/proj_dir
        run: |
           export PIP_DEFAULT_TIMEOUT=100
           export PY_VERSION=${{ matrix.python-version }}
           export PROJ_WHEEL=true
           export PROJ_NETWORK=ON
           export PROJ_VERSION=${{ env.PROJ_VERSION }}
           export PROJ_DIR=${{ env.PROJ_DIR }}
           export PROJ_LIB=${{ env.PROJ_DIR }}/share/proj
           export MACOSX_DEPLOYMENT_TARGET=10.9
           export CMAKE_OSX_ARCHITECTURES='arm64'
           export LDFLAGS="${LDFLAGS} -Wl,-rpath,${GITHUB_WORKSPACE}/pyproj/pyproj/proj_dir/lib"
           #
           echo "env of variable"
           env
           #
           echo "PROJ_DIR: " ${PROJ_DIR}
           echo "PROJ_DIR: " ${{ env.PROJ_DIR }}
           curl -L -v -o pyproj-3.3.1.tar.gz https://github.com/pyproj4/pyproj/archive/refs/tags/3.3.1.tar.gz
           tar -zxvf pyproj-3.3.1.tar.gz
           cp ./wheels/builders/proj-compile-wheels.sh pyproj-3.3.1/ci
           mv pyproj-3.3.1 pyproj
           cd pyproj
           echo "main folder `pwd`"
           pwd
           echo "======="
           #
           # compile proj
           #
           bash ./ci/proj-compile-wheels.sh
           #
           # test folder move to ~
           mv test ~/test${{ matrix.python-version }}
      - name: Set up Python${{ matrix.python-version }} with brew                                          
        run: |                                                                  
           brew install python@${{ matrix.python-version }}
      - name: Build wheels for Python${{ matrix.python-version }}
        env:
          PROJ_VERSION: "8.2.1"
          PROJ_DIR: ${GITHUB_WORKSPACE}/pyproj/pyproj/proj_dir
        run: |
           export PIP_DEFAULT_TIMEOUT=100
           export PROJ_WHEEL=true
           export PROJ_NETWORK=ON
           export PROJ_VERSION=${{ env.PROJ_VERSION }}
           export PROJ_DIR=${{ env.PROJ_DIR }}
           export PROJ_LIB=${{ env.PROJ_DIR }}/share/proj
           export MACOSX_DEPLOYMENT_TARGET=10.9
           export CMAKE_OSX_ARCHITECTURES='arm64'
           #
           cd ${GITHUB_WORKSPACE}/pyproj
           #
           echo "main folder `pwd`"
           pwd
           #
           python${{ matrix.python-version }} -m venv venv${{ matrix.python-version }}
           source venv${{ matrix.python-version }}/bin/activate
           pip install -U pip wheel setuptools delocate cython pytest 
           pip install -U oldest-supported-numpy pandas xarray
           #
           # make wheel
           #
           python -m pip wheel . --wheel-dir=./output${{ matrix.python-version }} --no-deps -vv
           echo "list of output folder `ls ./output${{ matrix.python-version }}`"
           delocate-listdeps ./output${{ matrix.python-version }}/*.whl 
           delocate-wheel --require-archs arm64 ./output${{ matrix.python-version }}/*.whl -w ~/repaired_wheel${{ matrix.python-version }}
           #
           echo "list of repaired_wheel folder `ls ~/repaired_wheel${{ matrix.python-version }}`"
           #  I can import proj fine if I'm not in the base directory for the pyproj project
           cd ~
           pip3 install ~/repaired_wheel${{ matrix.python-version }}/*.whl
           python3 -c "import pyproj; pyproj.Proj(init='epsg:4269')" 
           pip3 freeze
           echo "pyproj version"
           pyproj -v 
           #close venv
           deactivate
      - name: Upload artifacts for python${{ matrix.python-version }}
        uses: actions/upload-artifact@v2
        with:
          name: pyproj_whl
          path: ~/repaired_wheel${{ matrix.python-version }}/*.whl
          retention-days: 3
