name: Standalone tools wheels for oq-engine
on:
  workflow_dispatch:                                                           
    inputs:                                                                    
      git-ref:                                                                 
        description: Git Ref                                                   
        default: master                                                        
        required: true
  push:
    branches:    
      - tools
  #schedule:
    #- cron: "0 5 10 * 5"
jobs:

  Wheel_Tools:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    env:
      GIT_BRANCH: ${{ github.event.inputs.git-ref }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python  ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install engine and create wheel for tools
        env:
          GIT_BRANCH: ${{ github.event.inputs.git-ref }}
          GIT_COMMIT_SHA: ${{ github.sha }}
        run: |
          export PIP_DEFAULT_TIMEOUT=100
          branchname=master
          echo "clone engine and create wheel"
          export PIP_DEFAULT_TIMEOUT=100
          echo "Install engine with install script"
          echo "Branch: ${branchname}"
          echo "git clone --depth=1 -b ${branchname} https://github.com/gem/oq-engine.git"
          git clone --depth=1 -b ${branchname} https://github.com/gem/oq-engine
          python3.9 oq-engine/install.py devel
          echo "activate venv of oq-engine"
          source ~/openquake/bin/activate
          pip3 install --default-timeout=100 -U pip wheel setuptools
          echo "Downloading standalone apps"
          declare -a app=(oq-platform-standalone oq-platform-ipt oq-platform-taxonomy oq-platform-taxtweb)
          for element in "${app[@]}"
          do
              echo "${element}"
              echo "Branch: ${branchname}"
              echo "====================="
              echo "git clone --depth=1 -b ${branchname} https://github.com/gem/${element}"
              git clone --depth=1 -b ${branchname} https://github.com/gem/${element}
              pip3 wheel --disable-pip-version-check --no-deps -w ~/tools ./${element}
              if [[ "${element}" == "oq-platform-taxtweb" ]]; then
                PYBUILD_NAME="oq-taxonomy" pip3 wheel --disable-pip-version-check --no-deps -w ~/tools ./${element}
              fi
          done
          #                                
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: oq-engine_tools
          path: ~/tools
          retention-days: 5
  Upload_OQ_tools:
    runs-on: ubuntu-latest
    needs: Wheel_Tools
    steps: 
      - uses: actions/checkout@v2
      - name: Download OQ-engine tools from build job
        uses: actions/download-artifact@v2
        with:
          name: oq-engine_tools
      - name: rsync to downloads.openquake.org
        shell: bash
        env:
          DOWNLOAD_SSH: ${{ secrets.DOWNLOAD_ARTIFACTS }}
        run: |
          gpg --quiet --batch --yes --decrypt --passphrase="$DOWNLOAD_SSH" --output ./.deploy_rsa ./.oq_builders.enc
          chmod 600 ./.deploy_rsa
          eval $(ssh-agent -s) && ssh-add ./.deploy_rsa 
          rsync -e 'ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p 332' -ax OpenQuake_Engine* ftp@downloads.openquake.org:/var/www/wheelhouse/py/
