name: Windows Installer for oq-engine
on:
  push:
  schedule:
    - cron: "0 5 * * 5"
jobs:
  Windows-Installer:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        python-version: [3.8]
    steps:
      - name: Set up Python using embedded distribution
        run: |
          pwd
          curl  https://www.python.org/ftp/python/3.8.10/python-3.8.10-embed-amd64.zip --output python.zip
          where.exe unzip.exe
          unzip.exe python.zip -d python
          ls
          echo "install pip and wheel and setuptools"
          cd python
          curl https://bootstrap.pypa.io/get-pip.py --output get-pip.py
          .\python.exe .\get-pip.py
          mv .\python38._pth .\python38._pth.old
          $Env:PY_PIP = "D:\a\oq-builders\oq-builders\python\Scripts"
          $Env:PY_LIBS = "D:\a\oq-builders\oq-builders\python\Lib;D:\a\oq-builders\oq-builders\python\Lib\site-package"
          $Env:PY_HOME = "D:\a\oq-builders\oq-builders\python"
          $ENV:PATH="D:\a\oq-builders\oq-builders\python\Scripts;$ENV:PATH"
          dir env:
          python -c "import sys; print(sys.version)"
          where.exe python.exe
          cd ~
          git clone -q  --depth=1 https://github.com/gem/oq-builders
          cd .\oq-builders\installers\windows\nsis\
          pwd
          git clone --depth=1 https://github.com/gem/oq-engine.git
          cd oq-engine
          python -m pip install install -r requirements-py38-win64.txt
          python -m pip wheel --disable-pip-version-check --no-deps -w oq-dist/engine ./oq-engine
          echo "Downloading standalone apps"
          $app = ("oq-platform-standalone", "oq-platform-ipt", "oq-platform-taxonomy", "oq-platform-taxtweb")
          foreach ($element in $app) {
              git clone -q --depth=1 https://github.com/gem/$element.git
              python -m pip wheel --disable-pip-version-check --no-deps -w oq-dist/tools ./$element
              if ( $element -eq "oq-platform-taxtweb" ) 
              {
                #export PYBUILD_NAME="oq-taxonomy"
                $Env:PYBUILD_NAME = "oq-taxonomy"
                python -m pip -q wheel --disable-pip-version-check --no-deps -w oq-dist/tools ./$element
              }    
          }
      - name: Prepare Windows Installer 
        run: |
          cd ~
          cd .\oq-builders\installers\windows\nsis\
          pwd
          curl.exe -LO https://ci.openquake.org/job/builders/job/pdf-builder/lastSuccessfulBuild/artifact/oq-engine/doc/manual/oq-manual.pdf
          Rename-Item .\oq-manual.pdf "Openquake manual.pdf"
      - name: Upload wheel
        uses: actions/upload-artifact@v2
        with:
          name: Output Wheel
          path: C:\Users\runneradmin\oq-dist
