name: Windows Installer for oq-engine
on:
  push:
  schedule:
    - cron: "0 5 * * 5"
jobs:
  Windows-Installer:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        python-version: [3.8]
    steps:
      #- uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Upgrade pip, wheel and setuptools 
        run: |
          $PY_VER="py${{ matrix.python-version }}"
          $py = $PY_VER.replace(".","")
          python -m pip install pip wheel setuptools --upgrade
      - name: Create VENV for installation of engine and tools and display python version
        run: |
          python -m venv c:\Users\runneradmin\inst
          C:\Users\runneradmin\inst\Scripts\activate.ps1
          python -m pip install pip wheel setuptools --upgrade
          python -c "import sys; print(sys.version)"
          where.exe python.exe
      - name: Extracting python wheels for engine and for core apps
        run: |
          C:\Users\runneradmin\inst\Scripts\activate.ps1
          cd ~
          echo "Extracting python wheels"
          $PY_VER="py${{ matrix.python-version }}"
          $py = $PY_VER.replace(".","")
          git clone --depth=1 https://github.com/gem/oq-engine.git
          cd oq-engine
          python -m pip install install -r requirements-$py-win64.txt
          python -m pip install .
          cd ~
          mkdir oqdist
          python -m pip wheel --disable-pip-version-check --no-deps -w oq-dist/engine ./oq-engine
          echo "Downloading standalone apps"
          cd ~
          $app = ("oq-platform-standalone", "oq-platform-ipt", "oq-platform-taxonomy", "oq-platform-taxtweb")
          foreach ($element in $app) {
              git clone -q --depth=1 https://github.com/gem/$element.git
              python -m pip wheel --disable-pip-version-check --no-deps -w oq-dist/tools ./$element
              if ( $element -eq "oq-platform-taxtweb" ) 
              {
                #export PYBUILD_NAME="oq-taxonomy"
                $Env:PYBUILD_NAME = "oq-taxonomy"
                python -m pip -q wheel --disable-pip-version-check --no-deps -w oq-dist/tools ./$element
              }    
          }
      - name: Prepare Windows Installer 
        run: |
          C:\Users\runneradmin\inst\Scripts\activate.ps1
          cd ~
          ls 
          oq --version
          #cp oq-builder/installer/windows/nsis/installer.nsi.tmpl installer.nsi
      - name: Upload wheel
        uses: actions/upload-artifact@v2
        with:
          name: Output Wheel
          path: C:\Users\runneradmin\oqdist
